In [2]:
from bs4 import BeautifulSoup

In [3]:
import requests

In [4]:
url="https://en.m.wikipedia.org/wiki/List_of_tallest_buildings_in_India"

In [5]:
req=requests.get(url)

In [ ]:
tall=BeautifulSoup(req.text,"html")
tall

In [ ]:
table=tall.find("table")
print(table)

In [ ]:
tabhead=table.find_all('th')
print(tabhead)

In [ ]:
heading=[i.text for i in tabhead]
print(heading)

In [17]:
import pandas as pd

In [ ]:
mytall=pd.DataFrame(columns=heading)
print(mytall)

In [ ]:
tabrows=table.find_all('tr')
tabrows

In [ ]:
td=table.find_all('td')
td

In [ ]:
data=[i.text for i in td]
len(data)

In [ ]:
print(data[0:9])

In [41]:
start=0
stop=9
for i in range(len(data)//9):
  mytall.loc[i]=data[start:stop]
  start=start+9
  stop=stop+9
mytall

,Rank\n,Name\n,Image\n,City\n,Height\n,Floors\n,Year\n,Building type\n,Reference(s)\n
0,1\n,Palais Royale\n,\n,Mumbai\n,"320 metres (1,050 ft)\n",88\n,2018\n,Residential\n,[22]
1,2\n,Lokhandwala Minerva\n,\n,Mumbai\n,301 metres (988 ft)\n,78\n,2023\n,Residential\n,[23][24]
2,3\n,Piramal Aranya Arav\n,\n,Mumbai\n,282.2 metres (926 ft)\n,83\n,2022\n,Residential\n,[25]
3,4\n,World One\n,\n,Mumbai\n,280.2 metres (919 ft)\n,76\n,2020\n,Residential\n,[4][26]
4,5\n,World View\n,\n,Mumbai\n,277.6 metres (911 ft)\n,73\n,2020\n,Residential\n,[27][28]
...,...,...,...,...,...,...,...,...,...
57,Residential\n,[122][123][124],78\n,Piramal Aranya Avyan\n,\n,Mumbai\n,192.9 metres (633 ft)\n,52\n,2022\n
58,Residential\n,[125],79\n,The Ruby\n,\n,Mumbai\n,191 metres (627 ft)\n,40\n,2011\n
59,Commercial\n,[126][127],80\n,Lodha Primero\n,\n,Mumbai\n,190 metres (623 ft)\n,52\n,2014\n
60,Residential\n,[128][129][130],81\n,Runwal Bliss 3\n,\n,Mumbai\n,190 metres (623 ft)\n,52\n,2022\n
61,Residential\n,[131][132][133],Runwal Bliss 4\n,\n,Runwal Bliss 5\n,\n,84\n,Dhaval Sunrise\n,\n

In [42]:
mytall.to_csv('Buildings.csv')